#ifndef EVENTS_H
#define EVENTS_H


enum Event 
{ 
	POWER_BUTTON_PRESSED_90W = 0, 
	POWER_BUTTON_PRESSED_180W = 1, 
	POWER_BUTTON_PRESSED_360W = 2, 
	POWER_BUTTON_PRESSED_600W = 3, 
	POWER_BUTTON_PRESSED_900W = 4, 
	START_BUTTON_PRESSED = 5, 
	STOP_BUTTON_PRESSED = 6, 
	TIME_BUTTON_PRESSED = 7, 
	MEMORY_BUTTON_PRESSED = 8, 
	DOOR_OPENED = 9, 
	DOOR_CLOSED = 10, 
	TIME_DIALED = 11, 
	CLOCK_TIMER_PASSED = 12, 
	UPDATE_TIME_TIMER_PASSED = 13, 
	UPDATE_POWER_TIMER_PASSED = 14, 
	COUNTDOWN_COMPLETE = 15, 
	RADIATOR_TURNED_OFF = 16 
};

#endif
